apiVersion: v2
name: t11-rabbitmq
description: RabbitMQ message broker for the t11 standalone DAQ sim
version: 2.2.0

# When we deploy with the edge-containers-cli we override this on the command line.
# Direct deployment with Helm will use the default beta value.
appVersion: 0.0.1b1

type: application

dependencies:
  - name: rabbitmq
    version: 2.3.8
    repository: https://groundhog2k.github.io/helm-charts/
