# A Helm Chart for an IOC instance
apiVersion: v2
name: epics-pvcs

version: 1.0.0

type: application

dependencies:
    - name: epics-pvcs
<<<<<<< before updating
      version: 5.13.0-beta.2
=======
      version: 5.13.0
>>>>>>> after updating
      repository: "oci://ghcr.io/epics-containers/charts"
