# basic IOC startup script to load ioc.db and the synoptic status PVs
cd "/epics/ioc"

epicsEnvSet EPICS_TZ GMT0BST

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

dbLoadRecords /epics/ioc/config/ioc.db
# <prefix>:STA records for each techui.yaml component, generated by the
# generate-synoptic-extras init container (techui-builder status)
dbLoadRecords /epics/opi/status.db
iocInit
