epics-gateways:
  # developer image for debugging no longer needed - defaults to helm chart version
  # image: ghcr.io/epics-containers/epics-gateways-developer:2026.3.18

  # use ixxdetector account for your beamline
  securityContext:
    runAsUser: REPLACE_WITH_ID
    runAsGroup: REPLACE_WITH_ID
